import type { WxSystemTemplatePreset } from './wx-template-preset.types'

export const BEFORE_MARRIAGE_PRESET = {
	key: 'before-marriage',
	name: '领证前必须摊开的20个问题',
	description:
		'感情可以浪漫，婚姻必须具体：钱、房子、孩子、父母、家务、疾病和最坏情况都要谈。',
	coverUrl: null,
	category: 'marriage',
	content: {
		questions: [
			{
				id: 'before-marriage-1',
				type: 'text',
				title: '别只说“幸福就好”：你理想婚姻里最具体的一天是什么样的？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-2',
				type: 'single',
				title: '婚后更希望采用哪种居住安排？',
				required: true,
				options: [
					'两人独立居住',
					'与男方父母同住',
					'与女方父母同住',
					'阶段性同住',
					'根据现实共同决定',
				],
			},
			{
				id: 'before-marriage-3',
				type: 'text',
				title: '关于住房、首付、房贷和产权，你认为怎样安排才公平？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-4',
				type: 'single',
				title: '你倾向怎样管理婚后收入？',
				required: true,
				options: [
					'全部共同管理',
					'共同账户加个人账户',
					'收入各自管理，共同承担家庭支出',
					'由一方统一管理',
					'还需要共同讨论',
				],
			},
			{
				id: 'before-marriage-5',
				type: 'text',
				title: '双方目前的收入、存款、负债、贷款及固定家庭支出分别是什么情况？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-6',
				type: 'single',
				title: '超过多大金额的支出需要双方共同决定？',
				required: true,
				options: [
					'1000元',
					'5000元',
					'10000元',
					'根据家庭收入约定',
					'无需约定',
				],
			},
			{
				id: 'before-marriage-7',
				type: 'single',
				title: '你目前对生育的明确想法是什么？',
				required: true,
				options: [
					'希望有一个孩子',
					'希望有两个或更多孩子',
					'倾向不生育',
					'尚未决定',
					'尊重双方共同决定',
				],
			},
			{
				id: 'before-marriage-8',
				type: 'text',
				title: '如果生育困难、孕产风险较高或无法自然生育，你希望怎样共同面对？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-9',
				type: 'multiple',
				title: '如果有孩子，你认为育儿责任应包括哪些共同投入？',
				required: true,
				options: [
					'夜间照护',
					'接送与陪伴',
					'教育决策',
					'经济投入',
					'生病照护',
					'家校沟通',
				],
			},
			{
				id: 'before-marriage-10',
				type: 'single',
				title: '家务劳动更适合怎样分配？',
				required: true,
				options: [
					'尽量平均分担',
					'按擅长和时间分工',
					'一方多承担、另一方补偿',
					'请家政并共同承担费用',
					'暂未考虑',
				],
			},
			{
				id: 'before-marriage-11',
				type: 'text',
				title: '如果一方因生育或照护家庭失去晋升机会和收入，另一方准备怎样补偿？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-12',
				type: 'single',
				title: '如果父母强烈反对夫妻共同作出的决定，你最终听谁的？',
				required: true,
				options: [
					'可以建议，最终由夫妻决定',
					'重大事情需要听从父母',
					'根据出资或实际情况决定',
					'需要逐件商量',
				],
			},
			{
				id: 'before-marriage-13',
				type: 'text',
				title: '未来双方父母的养老、医疗和经济支持准备怎样安排？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-14',
				type: 'single',
				title: '春节及重要节日通常希望怎样安排？',
				required: true,
				options: [
					'双方家庭轮流',
					'以小家庭为主分别探望',
					'每年共同商量',
					'主要回一方家庭',
					'可以各自回家',
				],
			},
			{
				id: 'before-marriage-15',
				type: 'multiple',
				title: '婚前愿意共同完成哪些健康沟通？',
				required: true,
				options: [
					'婚前体检',
					'重大疾病史',
					'遗传病家族史',
					'心理健康情况',
					'生育相关检查',
					'生活习惯与成瘾风险',
				],
			},
			{
				id: 'before-marriage-16',
				type: 'multiple',
				title: '你认为婚姻中必须零容忍的行为有哪些？',
				required: true,
				options: [
					'任何形式的暴力',
					'威胁或恐吓',
					'持续羞辱贬低',
					'出轨或长期暧昧',
					'赌博或隐瞒巨额债务',
					'限制正常社交和人身自由',
				],
			},
			{
				id: 'before-marriage-17',
				type: 'single',
				title: '同一个问题吵了一年都没解决，你愿意咨询专业人士，还是认为家丑不可外扬？',
				required: true,
				options: [
					'愿意接受婚姻咨询',
					'可以先找可信赖的第三方',
					'更希望只在两人之间解决',
					'暂不确定',
				],
			},
			{
				id: 'before-marriage-18',
				type: 'text',
				title: '关于婚礼、彩礼、嫁妆和相关支出，双方能接受的方案是什么？',
				required: true,
				options: [],
			},
			{
				id: 'before-marriage-19',
				type: 'single',
				title: '你怎么看待婚前财产协议或书面约定？',
				required: true,
				options: [
					'愿意理性讨论并签署',
					'特定情况下可以考虑',
					'不希望签署',
					'不了解，需要先咨询',
				],
			},
			{
				id: 'before-marriage-20',
				type: 'text',
				title: '如果婚后出现失业、重病、照护压力或重大经济变化，希望双方怎样承担？',
				required: true,
				options: [],
			},
		],
		settings: {
			category: 'before-marriage',
			audience: 'women',
			estimatedMinutes: 20,
			disclaimer:
				'建议双方分别作答后逐项沟通；涉及健康、财务和法律问题时，应在尊重隐私的前提下核实并咨询专业人士。',
		},
	},
} satisfies WxSystemTemplatePreset
