import type { WxSystemTemplatePreset } from './wx-template-preset.types'

export const BLIND_DATE_BEFORE_MEETING_PRESET = {
	key: 'blind-date-before-meeting',
	name: '相亲别只问吃了吗',
	description:
		'把婚恋目标、经济现状、家庭边界和生活习惯问清楚，不浪费彼此时间，也不替对方脑补答案。',
	coverUrl: null,
	category: 'blind_date',
	content: {
		questions: [
			{
				id: 'blind-date-1',
				type: 'text',
				title: '你来相亲是自己主动想结婚，还是家里催得没办法？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-2',
				type: 'text',
				title: '如果遇到合适的人，你理想中从认识到结婚需要多久？为什么？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-3',
				type: 'text',
				title: '请坦诚说明目前的婚姻状态、重要感情经历，以及是否有子女或未处理完的关系。',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-4',
				type: 'text',
				title: '你的收入稳定吗？目前有哪些负债、贷款或必须长期承担的家庭支出？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-5',
				type: 'single',
				title: '如果伴侣收入长期比你高很多，你最真实的态度是什么？',
				required: true,
				options: ['真心支持，不影响相处', '高兴但可能有压力', '希望对方减少工作照顾家庭', '很难接受', '需要看双方如何分工'],
			},
			{
				id: 'blind-date-6',
				type: 'text',
				title: '你能接受婚后和父母同住吗？如果父母强烈要求同住，你会怎么决定？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-7',
				type: 'text',
				title: '你父母能在多大程度上影响你的婚姻决定？如果他们不喜欢伴侣呢？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-8',
				type: 'multiple',
				title: '以下生活情况中，哪些真实存在于你的日常？',
				required: true,
				options: ['吸烟', '经常饮酒', '频繁应酬', '长期熬夜', '经常出差', '高额游戏或娱乐消费', '以上都没有'],
			},
			{
				id: 'blind-date-9',
				type: 'text',
				title: '你是否想要孩子？如果一方不想生、不能生或者生育风险很高，你会怎么办？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-10',
				type: 'text',
				title: '如果将来有孩子，你认为夜间照护、家务和接送主要应该由谁承担？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-11',
				type: 'text',
				title: '你上一次和伴侣发生严重矛盾时做了什么？冷战、争吵还是沟通解决？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-12',
				type: 'text',
				title: '如果伴侣明确指出你的家人越界，你会先维护家人还是先了解事实？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-13',
				type: 'text',
				title: '未来五年，你计划在哪座城市生活？事业、买房和家庭哪个更优先？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-14',
				type: 'text',
				title: '你最不能接受伴侣做什么？其中哪些是底线，哪些只是偏好？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-15',
				type: 'text',
				title: '你认为自己在亲密关系里最难相处的一面是什么？',
				required: true,
				options: [],
			},
			{
				id: 'blind-date-16',
				type: 'text',
				title: '如果了解三个月后发现不合适，你会坦诚结束，还是因为年龄和成本继续磨合？',
				required: true,
				options: [],
			},
		],
		settings: {
			category: 'blind_date',
			audience: 'adults',
			estimatedMinutes: 16,
			disclaimer: '回答只能作为沟通起点，涉及婚姻、负债和健康的重要信息仍需在双方同意下核实。',
		},
	},
} satisfies WxSystemTemplatePreset
