import type { WxSystemTemplatePreset } from './wx-template-preset.types'

export const LOVE_LANGUAGE_TEMPLATE_PRESET = {
	key: 'love-language',
	name: '男朋友求生欲终极考试',
	description:
		'前任、审美、偏爱、吵架和未来规划轮番上阵，看看他的答案能不能安全交卷。',
	coverUrl: null,
	category: 'boyfriend_challenge',
	content: {
		questions: [
			{
				id: 'boyfriend-challenge-1',
				type: 'text',
				title: '如果我和你前女友同时掉进水里，你先救谁？不许只回答“救你”。',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-2',
				type: 'text',
				title: '你前女友身上有没有哪一点比我好？请认真组织语言。',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-3',
				type: 'text',
				title: '她半夜突然给你发“我想你了”，你的第一反应和下一步分别是什么？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-4',
				type: 'text',
				title: '听说前女友现在过得很不好，你会心疼吗？会不会联系她？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-5',
				type: 'text',
				title: '她妈妈突然联系你，说女儿一直忘不了你，你准备怎么回复？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-6',
				type: 'text',
				title: '说实话，我素颜和化妆差别大吗？分别好看在哪里？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-7',
				type: 'text',
				title: '如果我胖二十斤，你还会爱我吗？你会怎么陪我面对变化？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-8',
				type: 'text',
				title: '如果全世界都误解我，连证据看起来都对我不利，你会先相信谁？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-9',
				type: 'text',
				title: '如果你妈妈和我发生矛盾，而且你认为双方都有问题，你会怎么处理？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-10',
				type: 'text',
				title: '纪念日当天撞上你期待一年的比赛决赛，你准备怎么安排？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-11',
				type: 'text',
				title: '你的朋友当着大家的面拿我开了一个让我不舒服的玩笑，你会怎么做？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-12',
				type: 'text',
				title: '我们吵架时，你朋友说“她就是矫情，别理她”，你会怎么回答？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-13',
				type: 'text',
				title: '如果我事业上突然比你成功很多，收入也高很多，你真实的感受是什么？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-14',
				type: 'text',
				title: '如果只能保留关于我的一个记忆，你会留下哪一个？',
				required: true,
				options: [],
			},
			{
				id: 'boyfriend-challenge-15',
				type: 'text',
				title: '你觉得现在对我是爱、习惯、依赖，还是三者都有？请分别解释。',
				required: true,
				options: [],
			},
		],
		settings: {
			category: 'boyfriend_challenge',
			audience: 'couples',
			estimatedMinutes: 15,
			disclaimer: '题目用于增加互动和了解边界，不建议把单个答案当作感情判决书。',
		},
	},
} satisfies WxSystemTemplatePreset
